from typing import Protocol, Any


class XViewCursor(Protocol):
    def goLeft(self, count: int, expand: bool) -> bool: ...
    def goRight(self, count: int, expand: bool) -> bool: ...
    def goUp(self, count: int, expand: bool) -> bool: ...
    def goDown(self, count: int, expand: bool) -> bool: ...
    def gotoStart(self, expand: bool) -> bool: ...
    def gotoEnd(self, expand: bool) -> bool: ...
    def gotoStartOfLine(self, expand: bool) -> bool: ...
    def gotoEndOfLine(self, expand: bool) -> bool: ...
    def gotoStartOfParagraph(self, expand: bool) -> bool: ...
    def gotoRange(self, range: Any, expand: bool) -> None: ...
    def getStart(self) -> Any: ...
    def getEnd(self) -> Any: ...
    def getPosition(self) -> Any: ...
    def getText(self) -> Any: ...
    def getString(self) -> str: ...
    def setString(self, text: str) -> None: ...
    def createTextCursorByRange(self, range: Any) -> Any: ...
    def isAtStartOfLine(self) -> bool: ...
    def jumpToStartOfPage(self) -> bool: ...
    def jumpToNextPage(self) -> bool: ...
    def jumpToPreviousPage(self) -> bool: ...
    def screenUp(self) -> bool: ...
    def screenDown(self) -> bool: ...
    def isCollapsed(self) -> bool: ...
    StatusIndicator: Any
